### ISSUE TITLE
About Missing Data (0 values)

### ISSUE THREAD

**Issue by imethanlee** [liyaguang/DCRNN#59]
There is a lot of missing data (those with value 0) in both datasets (METR-LA and PEMS-BAY). Did you adopt any interplolation approach (such as linear interplolation) to fill in these missing values?
![an example of missing values](https://user-images.githubusercontent.com/36200682/112755455-5a60be00-9013-11eb-8b29-565bd7ffed21.png)

**Comment by liyaguang** [comment]
Thanks for the question. We don't do specific imputation/interpolation in the data, instead observations with label/groundtruth being 0 are ignored in the calculation of both loss and metric.

**Comment by Aniq55** [comment]
Does a **zero** observation in `METR-LA` and `PEMS-BAY` always indicate missing values?
It could also mean the following:
- No vehicle passed by in the 5min interval, so the recording is zero
-  There is a traffic jam due to which the cars are stuck and not moving, giving velocity zero

Moreover, why does a sensor fault always result in a zero value? The missing values should be presented in the data as NaN for clarity.
