### ISSUE TITLE
Chebyshev polynomial

### ISSUE THREAD

**Issue by meirena123** [liyaguang/DCRNN#61]
I just saw you use this picture when answering other people's questions.

![image](https://user-images.githubusercontent.com/82369114/114705120-f865bf80-9d59-11eb-9d14-ec37fce5584e.png)

There seems to be a problem with the coefficient in the formula in the appendix of your paper。
The coefficient of the first term on the right side of the equation below seems to be wrong, because the coefficient in your code is 2.
![image](https://user-images.githubusercontent.com/82369114/114705854-c99c1900-9d5a-11eb-97bf-b41f12a606a4.png)

**Comment by liyaguang** [comment]
Thanks for the kind efforts in identifying the issue. This is a typo in the Appendix, and the correct recurrence formula should be:
<img src="https://render.githubusercontent.com/render/math?math=T_k(x)=2xT_{k-1}(x)-T_{k-2}(x)"> with the coefficient being 2x instead of x, which aligns with the implementation.
