### ISSUE TITLE
Run the Pre-trained Model (Error)

### ISSUE THREAD

**Issue by bran170294** [liyaguang/DCRNN#7]
hi, I found this error when am trying to run the code
![image](https://user-images.githubusercontent.com/39514039/43687641-3a41f96a-990b-11e8-8322-a8be5adb085e.png)

did I miss something?

**Comment by liyaguang** [comment]
Hi Brahman,   this error may because you are creating the same mode multiple times (for example in the jupyter notebook). You may run the scripts instead:
`python dcrnn_train.py --config_filename=data/model/dcrnn_config.yaml` 

Besides, you may try to update the tensorflow-gpu to the latest version.
